name: charmin
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  firebase_messaging: ^14.2.2
  flutter_local_notifications: ^13.0.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.1
  flutter_quill: ^6.3.2
  go_router: ^6.0.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  logger: ^1.1.0
  timeago: ^3.3.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.17
  package_info_plus: ^3.0.3
  flutter_svg: ^1.0.1
  flutter_spinkit: ^5.1.0
  google_sign_in: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
